- hosts: localhost
  tasks:
    - name: ensure bluetooth firmware exists
      copy:
        src: files/BCM.hcd 
        dest: /lib/firmware/brcm/BCM.hcd
        force: no
    - name: ensure user mymzbe exists
      user:
        name: mymzbe
        shell: /bin/bash
        groups: wheel
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
    - name: ensure password gorilla desktop shortcut exists
      copy:
        src: files/pg.desktop
        dest: /home/mymzbe/Desktop/pg.desktop
    - name: ensuer userapps dir exists
      file:
        path: /home/mymzbe/userapps
        state: directory
        mode: 0755
    - name: ensure password gorilla binary installed
      copy:
        src: files/.pg.png
        dest: /home/mymzbe/userapps/.pg.png
        owner: mymzbe
        group: mymzbe
        mode: u=rwx,g=rwx,o=r
      copy:
        src: files/gorilla1537_64.bin
        dest: /home/mymzbe/userapps/gorilla1537_64.bin
        owner: mymzbe
        group: mymzbe
        mode: u=rwx,g=rwx,o=r


    

